fsd_label_all = [
    'electric guitar', 
    'coin dropping', 
    'vehicle horn', 
    'car passing by', 
    'traffic noise', 
    'idling', 
    'slam', 
    'bark', 
    'engine starting', 
    'tap', 
    'chirp and tweet', 
    'motor vehicle', 
    'siren', 
    'bicycle bell', 
    'vehicle accelerating', 
    'crackle', 
    'truck', 
    'sneeze', 
    'keys jangling', 
    'tick', 
    'raindrop', 
    'dish', 
    'liquid filling', 
    'glass', 
    'rattle', 
    'cutlery', 
    'crushing', 
    'wind chime', 
    'water', 
    'stream', 
    'hiss', 
    'water tap', 
    'cricket', 
    'drip', 
    'boiling', 
    'trickle and dribble', 
    'meow', 
    'shatter', 
    'squeak', 
    'alarm', 
    'sliding door', 
    'typewriter', 
    'bus', 
    'footsteps', 
    'tick-tock', 
    'thunder', 
    'ringtone', 
    'screech', 
    'doorbell', 
    'seafull', 
    'fixed-wing aircraft', 
    'chink and clink', 
    'zipper', 
    'glockenspiel', 
    'buzz', 
    'subway', 
    'marimba', 
    'microwave oven', 
    'food frying', 
    'door', 
    'run', 
    'church bell', 
    'ratchet and pawl', 
    'bathtub filling or washing', 
    'gong', 
    'fart', 
    'writing', 
    'acoustic guitar',
    'guitar', 
    'bass guitar', 
    'bass drum', 
    'tambourine', 
    'hands', 
    'crack', 
    'sink filling or washing', 
    'computer keyboard', 
    'wind', 
    'waves and surf', 
    'motorcycle', 
    'scissors', 
    'skateboard', 
    'gunshot', 
    'bird', 
    'sawing', 
    'cowbell', 
    'power tool', 
    'whoosh', 
    'organ', 
    'musical keyboard', 
    'piano', 
    'harp', 
    'hi-hat', 
    'trumpet', 
    'bell', 
    'harmonica', 
    'clapping', 
    'crash cymbal', 
    'tabla', 
    'scratching (performance technique)', 
    'explosion', 
    'mechanical fan', 
    'engine', 
    'printer', 
    'race car', 
    'hammer', 
    'chewing', 
    'gurgling', 
    'cupboard open or close', 
    'knock', 
    'wood', 
    'drawer open or close', 
    'wind instrument', 
    'accordion', 
    'burping', 
    'drum', 
    'snare drum', 
    'fire',
    'purr', 
    'brass instrument', 
    'cat', 
    'rain', 
    'cymbal', 
    'drill',
    'mallet percussion', 
    'chime', 
    'pour', 
    'mechanisms', 
    'train', 
    'finger snapping', 
    'percussion', 
    'clock', 
    'crumpling and crinkling', 
    'packing tape', 
    'growling', 
    'fireworks', 
    'dog', 
    'plucked string instrument', 
    'insect', 
    'breathing', 
    'tearing', 
    'car', 
    'splatter', 
    'gasp', 
    'bowed string instrument', 
    'ocean', 
    'rattle instrument', 
    'thump and thud', 
    'cough', 
    'strum', 
    'chicken', 
    'telephone', 
    'bicycle', 
    'crow', 
    'toilet flush', 
    'camera', 
    'typing', 
    'boom', 
    'aircraft', 
    'boat', 
    'frog', 
    'thunderstorm', 
    'liquid', 
    'tools', 
    'respiratory sounds', 
    'music', 
    'wild animals', 
    'rail transport', 
    'musical instrument', 
    'living', 
    'livestock', 
    'fowl'
]

fsd_label_unseen = [
    'coin dropping', 
    'tap', 
    'bicycle bell',  
    'crackle', 
    'truck', 
    'sneeze', 
    'keys jangling', 
    'tick', 
    'dish', 
    'liquid filling', 
    'glass', 
    'rattle', 
    'water tap', 
    'drip', 
    'boiling', 
    'trickle and dribble', 
    'shatter',  
    'tick-tock', 
    'screech', 
    'doorbell', 
    'seagull', 
    'chink and clink', 
    'zipper', 
    'marimba', 
    'microwave oven', 
    'food frying', 
    'run', 
    'ratchet and pawl', 
    'bathtub filling or washing', 
    'fart',  
    'hands',  
    'sink filling or washing', 
    'scissors', 
    'cowbell', 
    'power tool', 
    'whoosh', 
    'musical keyboard', 
    'hi-hat', 
    'clapping',  
    'chewing', 
    'gurgling', 
    'knock', 
    'wind instrument', 
    'burping',
    'brass instrument',  
    'drill',
    'mallet percussion', 
    'pour', 
    'mechanisms', 
    'finger snapping',
    'crumpling and crinkling', 
    'packing tape', 
    'plucked string instrument', 
    'insect', 
    'breathing', 
    'tearing',  
    'bowed string instrument', 
    'rattle instrument', 
    'thump and thud', 
    'cough',  
    'camera', 
    'boom', 
    'tools', 
    'respiratory sounds', 
    'wild animals', 
    'living', 
    'livestock'
]